
# Centralized SQL queries for the app
select:
  expenses: "SELECT id, category, sub_category, amount, date, spent_by, comments, receipt_path, receipt_blob FROM expenses WHERE status='active' ORDER BY category, sub_category"
  payment_details: "SELECT id, name, amount, date, comments, payment_type FROM payment_details ORDER BY date DESC, id DESC"
  total_payments: "SELECT COALESCE(SUM(amount),0) FROM payment_details"
  total_expenses: "SELECT COALESCE(SUM(amount),0) FROM expenses WHERE status='active'"
  sponsorship_items: "SELECT item FROM sponsorship_items"
  notification_emails: "SELECT email FROM notification_emails"
  expense_summary_by_person: "SELECT spent_by, SUM(amount) FROM expenses WHERE status='active' GROUP BY spent_by ORDER BY SUM(amount) DESC"
  prasad_seva_metrics: "SELECT seva_date, pooja_time, SUM(num_people) FROM prasad_seva WHERE status='active' GROUP BY seva_date, pooja_time"
  prasad_seva_total_sponsored: "SELECT SUM(num_people) FROM prasad_seva WHERE status='active'"
  prasad_seva_sponsors_list: "SELECT id, seva_type, names, item_name, num_people, apartment, seva_date, pooja_time, created_by, status FROM prasad_seva WHERE status='active'"
  prasad_seva_total_served_by_name: "SELECT names, SUM(num_people) as total_served FROM prasad_seva WHERE status='active' GROUP BY names ORDER BY total_served DESC"
  prasad_seva_edit_delete_list: "SELECT id, seva_type, names, item_name, num_people, apartment, seva_date, pooja_time, created_by, status FROM prasad_seva WHERE status='active' ORDER BY seva_date, pooja_time, id"
  sponsors_list: "SELECT name, email, mobile, sponsorship, donation FROM sponsors ORDER BY id"
  notification_emails_valid: "SELECT email FROM notification_emails WHERE email IS NOT NULL AND email != ''"
  sponsorship_items_ordered: "SELECT item, amount, sponsor_limit FROM sponsorship_items ORDER BY id"
  sponsorship_counts: "SELECT sponsorship, COUNT(*) FROM sponsors GROUP BY sponsorship"
  events_list: "SELECT id, title, event_date, event_time, link, description FROM events ORDER BY event_date, event_time"
  sponsorship_and_donation: "SELECT sponsorship, donation FROM sponsors"
  sponsorship_only: "SELECT sponsorship FROM sponsors"
  paypal_payments: "SELECT amount FROM payment_details WHERE payment_type = 'PayPal'"
  zelle_payments: "SELECT amount FROM payment_details WHERE payment_type = 'Zelle'"
insert:
  expense_postgres: "INSERT INTO expenses (category, sub_category, amount, date, spent_by, comments, receipt_path, receipt_blob, status) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, 'active')"
  expense_snowflake: "INSERT INTO expenses (id, category, sub_category, amount, date, spent_by, comments, receipt_path, receipt_blob, status) VALUES (expenses_id_seq.NEXTVAL, %s, %s, %s, %s, %s, %s, %s, %s, 'active')"
  prasad_seva_postgres: "INSERT INTO prasad_seva (seva_type, names, item_name, num_people, apartment, seva_date, pooja_time, created_by, status) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
  prasad_seva_snowflake: "INSERT INTO prasad_seva (id, seva_type, names, item_name, num_people, apartment, seva_date, pooja_time, created_by, status) VALUES (prasad_seva_id_seq.NEXTVAL, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
  event_postgres: "INSERT INTO events (title, event_date, event_time, link, description) VALUES (%s, %s, %s, %s, %s)"
  event_snowflake: "INSERT INTO events (id, title, event_date, event_time, link, description) VALUES (events_id_seq.NEXTVAL, %s, %s, %s, %s, %s)"
  payment_detail: "INSERT INTO payment_details (name, amount, date, comments, payment_type) VALUES (%s, %s, %s, %s, %s)"
update:
update:
  expense_with_receipt: "UPDATE expenses SET category=%s, sub_category=%s, amount=%s, date=%s, spent_by=%s, comments=%s, receipt_path=%s, receipt_blob=%s, status='active' WHERE id=%s"
  expense_without_receipt: "UPDATE expenses SET category=%s, sub_category=%s, amount=%s, date=%s, spent_by=%s, comments=%s, status='active' WHERE id=%s"
  expense_delete_receipt: "UPDATE expenses SET receipt_path=NULL, receipt_blob=NULL WHERE id=%s"
  expense_set_inactive: "UPDATE expenses SET status='inactive' WHERE id=%s"
  prasad_seva_entry: "UPDATE prasad_seva SET seva_type=%s, names=%s, item_name=%s, num_people=%s, apartment=%s, seva_date=%s, pooja_time=%s, status=%s WHERE id=%s"
  prasad_seva_set_inactive: "UPDATE prasad_seva SET status='inactive' WHERE id=%s"
  event_entry: "UPDATE events SET title=%s, event_date=%s, event_time=%s, link=%s, description=%s WHERE id=%s"
  payment_detail: "UPDATE payment_details SET name=%s, amount=%s, date=%s, comments=%s, payment_type=%s WHERE id=%s"
delete:
  event_entry: "DELETE FROM events WHERE id=%s"
  expense: "UPDATE expenses SET status='inactive' WHERE id=%s"
  payment_detail: "DELETE FROM payment_details WHERE id=%s"
